spring:
  datasource:
    url: jdbc:mysql://localhost:3306/his
    username: root
    password: Shre@4348
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
